FROM ubuntu@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54 AS novnc-extractor

WORKDIR /tmp/novnc

# Use curl to download the archive to stdout, pipe to tar to extract it directly.
# Extract only the package.json file
# The 1.3.0 is used here for compatibility with older Ubuntu (22.04) version
RUN apt update \
    && apt install -y curl tar \
    && curl -sL "https://github.com/novnc/noVNC/archive/v1.3.0.tar.gz" | tar -xzf - "noVNC-1.3.0/package.json" \
    && mv "noVNC-1.3.0/package.json" ./package.json

# Ubuntu-based noVNC container with token auth and Firefox

# Ubuntu 22.04 LTS base image
FROM ubuntu@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54 AS production

ENV REFRESHED_AT=2026-01-08
ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1
ENV VNC_PORT=5901
ENV NOVNC_PORT=6901
ENV TERM=xterm
ENV STARTUPDIR=/dockerstartup
ENV INST_SCRIPTS=/headless/install
ENV NOVNC_HOME=/usr/share/novnc
ENV VNC_COL_DEPTH=24
ENV VNC_RESOLUTION=1920x1200
ENV VNC_PW=changeit
ENV XDG_CONFIG_HOME=/headless
ENV XDG_DESKTOP_DIR=/headless/Desktop
ENV MOZ_FORCE_DISABLE_E10S=1

# Install system dependencies
RUN apt-get update \
    && apt-get install -y \
    at-spi2-core \
    bzip2 \
    ca-certificates \
    curl \
    dbus-user-session \
    dbus-x11 \
    gnome-terminal \
    gpg-agent \
    firefox \
    jq \
    locales \
    mailcap \
    menu-xdg \
    net-tools \ 
    novnc \
    pm-utils \
    python3-numpy \
    python3-websockify \
    supervisor \
    tigervnc-common \
    tigervnc-standalone-server \
    tigervnc-tools \
    tigervnc-xorg-extension \
    twm \
    vim \
    websockify \
    wget \
    x11-xserver-utils \
    xdg-utils \
    xfce4 \
    xfce4-appfinder \
    xinit \
    xterm \
    --no-install-recommends \
    && mkdir -p /usr/lib/firefox/distribution \
    && printf '{ \
  "policies": { \
    "DisableAppUpdate": true, \
    "DisableFirefoxStudies": true \
  } \
}' > /usr/lib/firefox/distribution/policies.json \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Assume multiple user home directories are mounted under /home
WORKDIR /tmp

# CANFAR Specifics Below
COPY conf/xfce-applications.menu /etc/xdg/menus/xfce-applications.menu
COPY conf/xfce-applications.menu /etc/xdg/menus/applications.menu

# Add desktop icon files
RUN mkdir -p /headless/.icons \
    && mkdir -p /headless/Desktop \
    && chmod 777 /headless/Desktop \
    && mkdir -p /etc/xdg/menus/applications-merged \
    && chmod 777 /etc/xdg/menus/applications-merged

# create the guest account
RUN groupadd -g 30001 guest
RUN useradd -m -g guest -u 30001 guest && \
    mkdir -p /home/guest/.ssl && \
    chown -R guest:guest /home/guest/.ssl && \
    ln -s /home/guest/.ssl /headless/.ssl

RUN mkdir -p $XDG_CONFIG_HOME/.config
ADD ./src/common/xfce/.config/user-dirs.dirs $XDG_CONFIG_HOME/.config/
ADD ./src/common/xfce/.config/ $XDG_CONFIG_HOME/

# Add scripts that launch sofware containers
ADD software-scripts/*.sh /usr/local/bin/

ADD ./src/common/install/set_user_permission.sh $INST_SCRIPTS/
RUN chmod +x $INST_SCRIPTS/set_user_permission.sh

ADD ./src/common/scripts $STARTUPDIR/
RUN chmod +x $STARTUPDIR/*.sh

RUN $INST_SCRIPTS/set_user_permission.sh $STARTUPDIR /headless

COPY software-scripts/icons/* /headless/.icons

# Add desktop links to those scripts
COPY software-scripts/*.desktop /usr/share/applications/

# Add a subset of software links to the desktop
COPY --chown=guest:root software-scripts/arcade-feedback.desktop /headless/Desktop/arcade-feedback.desktop
COPY --chown=guest:root software-scripts/firefox.desktop /headless/Desktop/firefox.desktop
COPY --chown=guest:root software-scripts/gedit.desktop /headless/Desktop/gedit.desktop
COPY --chown=guest:root software-scripts/kill-session.desktop /headless/Desktop/kill-session.desktop

# Create firefox profile and space
# RUN mkdir -p /headless/mozilla/skaha
# RUN firefox --headless -CreateProfile "skaha /headless/mozilla/skaha"
# RUN chmod -R 777 /headless/mozilla/skaha

RUN rm /etc/xdg/Thunar/uca.xml
RUN rm -f /etc/xdg/autostart/xscreensaver.desktop

# Global VNC startup script (does not touch user HOME)
RUN mkdir -p /etc/vnc && \
    cat <<EOF > /etc/vnc/xstartup 
#!/bin/bash
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# BM
echo "about to source ${HOME}/.bashrc"

# should also source $STARTUPDIR/generate_container_user
source "${HOME}/.bashrc"

# Merge user .Xresources if it exists
if [ -f "${HOME}/.Xresources" ]; then
    xrdb -merge "${HOME}/.Xresources"
fi

mkdir -p /headless/.vnc
touch /headless/.vnc/passwd
chmod 600 /headless/.vnc/passwd
echo "${VNC_PW}" | vncpasswd -f >> /headless/.vnc/passwd

echo "Starting xfce4 session"

if [ -x /etc/X11/xinit/xinitrc ]; then
  exec /etc/X11/xinit/xinitrc
elif [ -f /etc/X11/xinit/xinitrc ]; then
  exec sh /etc/X11/xinit/xinitrc
fi

echo "Starting xfce4 session - done - setting xhost value"

# BM: disable x auth
xhost +


echo "Starting xfce4 session - done - setting xhost value - done"

# BM: disable screen saver
xset s noblank
xset s off

xterm -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &

EOF

RUN chmod 777 /etc/vnc/xstartup

# Supervisor setup
# This will need to be run as the current user, so make this writable
RUN mkdir -p /etc/supervisor/conf.d \
    && chmod -R 777 /etc/supervisor/conf.d \
    && mkdir -p /var/log/supervisor /var/run/supervisor \
    && chmod -R 0775 /var/log/supervisor /var/run/supervisor

VOLUME [ "/var/log/supervisor", "/var/run/supervisor" ]

# Supervisor configuration (no VNC password, token-based noVNC configuration)
# This will start both the VNC server and the noVNC web server, proxying the $NOVNC_PORT to localhost:VNC_PORT as specified in /etc/novnc/tokens (below)
# RUN printf "[supervisord]\nnodaemon=true\nlogfile=/var/log/supervisor/supervisord.log\npidfile=/var/run/supervisor/supervisord.pid\n\n[program:vnc]\ncommand=/usr/bin/tigervncserver :1 -localhost -cleanstale -verbose -xstartup /etc/vnc/xstartup -geometry ${VNC_RESOLUTION}\n\n[program:novnc]\ncommand=/usr/bin/websockify --web=/usr/share/novnc/ --token-plugin TokenFile --token-source /etc/novnc/tokens %d\n" "$NOVNC_PORT" > /etc/supervisor/conf.d/supervisord.conf
RUN printf "[supervisord]\nnodaemon=true\nlogfile=/var/log/supervisor/supervisord.log\npidfile=/var/run/supervisor/supervisord.pid\n\n[program:vnc]\ncommand=/usr/bin/tigervncserver :1 -localhost=0 -verbose -SecurityTypes None -depth %d -PasswordFile \${HOME}/.vnc/passwd -xstartup /etc/vnc/xstartup -geometry ${VNC_RESOLUTION}\n\n[program:novnc]\ncommand=${NOVNC_HOME}/utils/novnc_proxy --listen %d --vnc localhost:%d --web /usr/share/novnc\n" "${VNC_COL_DEPTH}" "${NOVNC_PORT}" "${VNC_PORT}" > /etc/supervisor/conf.d/supervisord.conf

# noVNC token configuration
# RUN mkdir -p /etc/novnc && \
#     echo "token1: localhost:$VNC_PORT" > /etc/novnc/tokens

RUN ln -s ${NOVNC_HOME}/vnc_lite.html ${NOVNC_HOME}/index.html
COPY --from=novnc-extractor /tmp/novnc/package.json ${NOVNC_HOME}/app/package.json
COPY --from=novnc-extractor /tmp/novnc/package.json ${NOVNC_HOME}/package.json

EXPOSE ${NOVNC_PORT}

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
