site_name: CANFAR Science Platform
site_url: https://opencadc.github.io/science-containers/
site_author: CANFAR
site_description: Documentation and Science Containers for the CANFAR Science Platform
repo_url: https://github.com/opencadc/science-containers/
repo_name: opencadc/science-containers
edit_uri: blob/main/docs/
copyright: Copyright &copy; 2023 CANFAR
remote_branch: gh-pages

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye-outline
  features:
    - tabs
    - instant
    - content.action.edit
    - offline
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - header.autohide
    - navigation.top

plugins:
  - search
  - tags
  - mkdocstrings
  - git-revision-date-localized:
        type: date
        fallback_to_build_date: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Contributing: CONTRIBUTING_DOCS.md # Link to the new contributing guide

  # Section 1: Quick Start Guide
  - Quick Start:
    - Get Access: user-guide/access.md
    - First Login: user-guide/first-login.md
    - Login Process: user-guide/login.md
    - Launch Your First Session: user-guide/launch-notebook.md # Assuming this is the primary launch guide
    - Basic File Operations: user-guide/transfer-file.md
    
  # Section 2: Core Concepts  
  - Core Concepts:
    - Platform Overview: user-guide/overview.md
    - Storage Systems Guide: storage-systems-guide.md
    - Container Types: user-guide/choose-interface.md
    - Project Spaces: user-guide/project-space.md
    
  # Section 3: Data Management
  - Data Management:
    - Complete Transfer Guide: data-transfer-guide.md
    - Web Interface: user-guide/web-file-manager.md
    - Command Line (sshfs): user-guide/sshfs-setup.md
    - VOSpace Tools: user-guide/vospace-tools.md
    - Direct URL Access: user-guide/direct-url.md
    - Group Management: user-guide/group-permissions.md
    
  # Section 4: Interactive Sessions
  - Interactive Sessions:
    - Jupyter Notebooks: user-guide/launch-notebook.md
    - Desktop Sessions: user-guide/launch-desktop.md
    - CARTA Visualization: user-guide/launch-carta.md
    - Desktop Tips & Tricks:
      - Clipboard Usage: user-guide/using-clipboard.md
      - Font Size: user-guide/increase-font.md
    - General Workflows:
      - Data Analysis: tutorials/data-analysis.md
      - Desktop Applications: tutorials/desktop-apps.md
    - Specialized Workflows:
      - Radio Astronomy: tutorials/radio-astronomy.md
      - ALMA Data Reduction:
        - Getting Started: tutorials/start-casa.md
        - Archive Downloads: tutorials/archive-download.md
        - Script Downloads: tutorials/archive-script-download.md
        - Typical Reduction: tutorials/typical-reduction.md
        - CASA Container Notes: tutorials/casa-containers.md
        
  # Section 5: Container Development
  - Container Development:
    - Building Guide: container-building-guide.md
    - Testing Containers: developer-guide/containers.md
    - Publishing Containers: reference-material/container-publishing-guide.md
    - Available Containers: reference-material/available-containers.md
    
  # Section 6: Batch & Automation
  - Batch & Automation:
    - Headless Execution: headless-execution-guide.md
    - API Access: developer-guide/api.md
    - Batch Processing: developer-guide/batch.md
    
  # Section 7: Administration
  - Administration:
    - User Permissions: developer-guide/permissions.md # was advanced/permissions.md
    - Platform Infrastructure: reference-material/platform-infrastructure.md
    - Portal Administration: reference-material/portal-administration.md
    - API Authorizations: reference-material/permissions.md # was complete/permissions.md
    
  # Section 8: Reference & Support
  - Reference & Support:
    - FAQ: help/faq.md
    - Community Support: https://cadc.slack.com/archives/C01K60U5Q87
    - Email Support: mailto:support@canfar.net
    - Report Issues: https://github.com/opencadc/science-platform/issues
