site_name: CANFAR Science Platform
site_url: https://opencadc.github.io/science-containers/
site_author: CANFAR
site_description: Documentation and Science Containers for the CANFAR Science Platform
repo_url: https://github.com/opencadc/science-containers/
repo_name: opencadc/science-containers
edit_uri: blob/main/docs/
copyright: Copyright &copy; 2023 CANFAR
remote_branch: gh-pages

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye-outline
  features:
    - tabs
    - instant
    - content.action.edit
    - offline
    - navigation.sections
    #- navigation.expand

plugins:
  - search
  - mkdocstrings
  - git-revision-date-localized:
        type: date
        fallback_to_build_date: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  
  # Section 1: Quick Start Guide
  - Quick Start:
    - Get Access: getting-started/access.md
    - First Login: getting-started/first-login.md
    - Login Process: general/NewUser/login.md
    - Launch Your First Session: general/NewUser/launch-notebook.md
    - Basic File Operations: general/Notebook/transfer-file.md
    
  # Section 2: Core Concepts  
  - Core Concepts:
    - Platform Overview: general/NewUser/overview.md
    - Storage Systems Guide: storage-systems-guide.md
    - Container Types: getting-started/choose-interface.md
    - Project Spaces: general/NewUser/project-space.md
    
  # Section 3: Data Management
  - Data Management:
    - Complete Transfer Guide: data-transfer-guide.md
    - Web Interface: general/General_tools/web-file-manager.md
    - Command Line (sshfs): general/General_tools/sshfs-setup.md
    - VOSpace Tools: general/General_tools/vospace-tools.md
    - Direct URL Access: general/TipsTricks/direct-url.md
    - Group Management: general/General_tools/group-permissions.md
    
  # Section 4: Interactive Sessions
  - Interactive Sessions:
    - Jupyter Notebooks: general/NewUser/launch-notebook.md
    - Desktop Sessions: general/NewUser/launch-desktop.md
    - CARTA Visualization: general/NewUser/launch-carta.md
    - Desktop Tips & Tricks:
      - Clipboard Usage: general/TipsTricks/using-clipboard.md
      - Font Size: general/TipsTricks/increase-font.md
    - General Workflows:
      - Data Analysis: tutorials/data-analysis.md
      - Desktop Applications: tutorials/desktop-apps.md
    - Specialized Workflows:
      - Radio Astronomy: tutorials/radio-astronomy.md
      - ALMA Data Reduction:
        - Getting Started: general/ALMA_Desktop/start-casa.md
        - Archive Downloads: general/ALMA_Desktop/archive-download.md
        - Script Downloads: general/ALMA_Desktop/archive-script-download.md
        - Typical Reduction: general/ALMA_Desktop/typical-reduction.md
        - CASA Container Notes: general/ALMA_Desktop/casa-containers.md
        
  # Section 5: Container Development
  - Container Development:
    - Building Guide: container-building-guide.md
    - Testing Containers: advanced/containers.md
    - Publishing Containers: complete/container-publishing-guide.md
    - Available Containers: complete/available-containers.md
    
  # Section 6: Batch & Automation
  - Batch & Automation:
    - Headless Execution: headless-execution-guide.md
    - API Access: advanced/api.md
    - Batch Processing: advanced/batch.md
    
  # Section 7: Administration
  - Administration:
    - User Permissions: advanced/permissions.md
    - Platform Infrastructure: complete/platform-infrastructure.md
    - Portal Administration: complete/portal-administration.md
    - API Authorizations: complete/permissions.md
    
  # Section 8: Reference & Support
  - Reference & Support:
    - FAQ: help/faq.md
    - Community Support: https://cadc.slack.com/archives/C01K60U5Q87
    - Email Support: mailto:support@canfar.net
    - Report Issues: https://github.com/opencadc/science-platform/issues
