site_name: CANFAR Science Platform
site_url: https://opencadc.github.io/science-containers/
site_author: CANFAR
site_description: Documentation and Science Containers for the CANFAR Science Platform
repo_url: https://github.com/opencadc/science-containers/
repo_name: opencadc/science-containers
edit_uri: blob/main/docs/
copyright: Copyright &copy; 2023 CANFAR
remote_branch: gh-pages

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  icon:
    repo: fontawesome/brands/github-alt
    edit: material/pencil-box
    view: material/eye-outline
  features:
    - tabs
    - instant
    - content.action.edit
    - offline
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - toc.integrate
    - header.autohide
    - navigation.top

plugins:
  - search
  - tags
  - mkdocstrings
  - git-revision-date-localized:
        type: date
        fallback_to_build_date: true

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums_style: pymdownx.inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md

  # Getting Started - Quick 10-minute setup
  - Getting Started: get-started/index.md

  # Comprehensive User Guide organized by topic
  - User Guide:
    - user-guide/index.md
    - Platform Concepts: user-guide/concepts/index.md
    - Accounts & Permissions: user-guide/accounts-permissions/index.md
    - Storage Systems: 
      - user-guide/storage/index.md
      - VOSpace API: user-guide/storage/vospace-api.md
    - Container Usage: user-guide/containers/index.md
    - Interactive Sessions:
      - user-guide/interactive-sessions/index.md
      - Jupyter Notebooks: user-guide/interactive-sessions/launch-notebook.md
      - Desktop Sessions: user-guide/interactive-sessions/launch-desktop.md
      - CARTA Visualization: user-guide/interactive-sessions/launch-carta.md
      - Firefly Table Viewer: user-guide/interactive-sessions/launch-firefly.md
      - Contributed Applications: user-guide/interactive-sessions/launch-contributed.md
    - Batch Jobs: user-guide/batch-jobs/index.md
    - Radio Astronomy: 
      - user-guide/radio-astronomy/index.md
      - CASA Workflows: user-guide/radio-astronomy/casa-workflows.md

  # FAQ covering common questions and troubleshooting
  - FAQ: faq/index.md

  # Help and Support Resources
  - Help & Support: help/index.md

  # Legacy Content (tutorials and specialized guides)
  - Legacy Documentation:
    - Desktop Tips:
      - Clipboard Usage: user-guide/using-clipboard.md
      - Font Size: user-guide/increase-font.md
    - Project Management: user-guide/project-space.md
